### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by urobasa** [TwrpBuilder/twrpbuilder_tree_generator#10]
No private recovery resources for TARGET_DEVICE vu3
build/core/Makefile:993: device/generic/twrpbuilder/mkbootimg_lz4.mk: No such file or directory
build/core/tasks/kernel.mk:104: ***************************************************************
build/core/tasks/kernel.mk:105: * Using prebuilt kernel binary instead of source              *
build/core/tasks/kernel.mk:106: * THIS IS DEPRECATED, AND WILL BE DISCONTINUED                *
build/core/tasks/kernel.mk:107: * Please configure your device to download the kernel         *
build/core/tasks/kernel.mk:108: * source repository to kernel/lge/vu3
build/core/tasks/kernel.mk:109: * See http://forum.xda-developers.com/wiki/ROM/Integrated_Kernel_Build
build/core/tasks/kernel.mk:110: * for more information                                        *
build/core/tasks/kernel.mk:111: ***************************************************************
make: *** No rule to make target 'device/generic/twrpbuilder/mkbootimg_lz4.mk'.  Stop.

**Comment by androidlover5842** [comment]
clone this https://github.com/TwrpBuilder/android_device_generic_twrpbuilder
