### ISSUE TITLE
failed to get codeName

### ISSUE THREAD

**Issue by Shijikori** [TwrpBuilder/twrpbuilder_tree_generator#11]
Hello, I am trying to make a recovery.img for my SM-J327W and I have an error about the code name. I followed all the steps on the wiki but this is what I get when trying to get the device tree :
```
mikasu@Aspire-V3-572PG:~/twrp$ java -jar TwrpBuilder-1.0-SNAPSHOT.jar  -r recovery.img
Building tree using: recovery.img
Found gzip comression in ramdisk
Dir: device/motorola// already exist
Failed to get codeName
mikasu@Aspire-V3-572PG:~/twrp$ java -jar TwrpBuilder-1.0-SNAPSHOT.jar  -r recovery.img -t samsung
Building tree using: recovery.img
Found gzip comression in ramdisk
Dir: device/motorola// already exist
Failed to get codeName
mikasu@Aspire-V3-572PG:~/twrp$ 
```

(this is what I did on my CLI with the output of the commands I tried)
Could it be because of the recovery.img? I picked up one from somewhere on Internet by searching "android recovery.img" on DuckDuckGo

**Comment by MuhammedSheref** [comment]
maybe, use stock recovery.img of that device.

https://twrpbuilder.github.io/downloads/twrp/#361 
Already twrp is available for your device. Test that recovery.

**Comment by Shijikori** [comment]
@MuhammedSheref I tested it, the screen wouldn't work, it only displays. It was one from androidlover though. It's date was 030418. I'll test it but I guess I got the wrong recovery.img then. I'll try to find that.

**Comment by Shijikori** [comment]
@MuhammedSheref the recovery.img from your link didn't work either. It would not register the inputs from the screen like the other one.
So I guess I have to find the stock recovery then.

**Comment by Shijikori** [comment]
So is there any ways to get a recovery image out of a .tar.md5 AP file? That's all I have from the stock firmware of the phone (with BL, CP and CSC).

**Comment by surendrajat** [comment]
@Mikasu-X14 remove `.md5` and extract it like a normal `.tar` file. You may find stock `recovery.img` inside it.

**Comment by Shijikori** [comment]
Thank you @Surendrajat but I got a recovery.img.lz4, how do I get rid of .lz4? Do I just remove it too?

**Comment by surendrajat** [comment]
@Mikasu-X14 No. Google about extracting `.lz4` files.

**Comment by Shijikori** [comment]
got it, let's see how it goes...

**Comment by Shijikori** [comment]
Ok, so it pretty much made it to the end... but I got that message : `#### make failed to build some targets (02:28 (mm:ss)) ####
` should I be worried about that?

**Comment by surendrajat** [comment]
If you're sane, YES!

**Comment by Shijikori** [comment]
Here is the error output :
```
mikasu@Aspire-V3-572PG:~/twrp$ LC_ALL=C make -j4 recoveryimage
cc1: all warnings being treated as errors
target Strip: libexfat_twrp (/home/mikasu/twrp/out/target/product/j3popeltecan/obj/lib/libexfat_twrp.so)
build/core/binary.mk:700: recipe for target '/home/mikasu/twrp/out/host/linux-x86/obj32/EXECUTABLES/checkseapp_intermediates/check_seapp.o' failed
make: *** [/home/mikasu/twrp/out/host/linux-x86/obj32/EXECUTABLES/checkseapp_intermediates/check_seapp.o] Error 1
make: *** Waiting for unfinished jobs....
target Strip: init (/home/mikasu/twrp/out/target/product/j3popeltecan/obj/EXECUTABLES/init_intermediates/init)

#### make failed to build some targets (16 seconds) ####

```

**Comment by Shijikori** [comment]
@Surendrajat i am sane and that's why I asked if about it. So I just gave the whole output just in case that's something that I did wrong or an argument that I forgot

**Comment by surendrajat** [comment]
@Mikasu-X14 Check the [troubleshooting section](https://github.com/TwrpBuilder/twrpbuilder_tree_generator/wiki#troubleshooting) of the wiki.

**Comment by fawazahmed0** [comment]
@Surendrajat @Mikasu-X14 I too am getting 'Failed to get 'CodeName' Error, 
I am using ubuntu 18.04 64bit, openjdk 8
Any clue?

**Comment by Shijikori** [comment]
Alright! Successful! So now I just put the output recovery.img on my phone to send it to TwrpBuilders with the app @Surendrajat ?

**Comment by Shijikori** [comment]
@fawazahmed0 do you have stock firmware, rom or recovery of your device? Because the wiki says any but you actualy need your device's recovery image.

**Comment by fawazahmed0** [comment]
@Mikasu I was able to solve the problem, I was using stock recovery, the problem was in the twrpbuilder code itself

**Comment by Shijikori** [comment]
@fawazahmed0 yeah, there is a modification you need to do in the code if you have 17.10+

**Comment by fawazahmed0** [comment]
@Mikasu-X14  you can also compile twrp yourself, see this: https://forum.xda-developers.com/showthread.php?t=1943625
Guide is not user friendly, but if you are good at linux, then you can do it, ask help if needed

**Comment by Shijikori** [comment]
I'll request it. I am not that experienced for this. Eventhough I use Mint 19.1 daily since I hate Windows 10.

**Comment by fawazahmed0** [comment]
@Surendrajat  My recovery.img had default.prop as prop.default, thats why the code was not working, had to do some changes in Tools.java code
` else if (new File(out + "default.prop").exists()) {
            prop = out + "default.prop";
        } else if(new File(out + "prop.default").exists()){
        	prop = out + "prop.default";
        }
        else {
            prop = "null";
        }`


Now its working

**Comment by Shijikori** [comment]
or maybe you could've renamed the file but you got it working :)

**Comment by fawazahmed0** [comment]
@Mikasu-X14  Renaming was not possible, prop.default was packed inside recovery.img

**Comment by Shijikori** [comment]
I see. Do you know if I just have to send the output recovery.img through the app or there is other things?

**Comment by fawazahmed0** [comment]
> 
> 
> I see. Do you know if I just have to send the output recovery.img through the app or there is other things?

@Mikasu-X14  I think through app, but, it will say something like devices in queue, so you have to wait
Why don't you do yourself, I will help you, I will tell you the procedure I followed,  if you say so

**Comment by Shijikori** [comment]
I'll watch the queue. I am going to be busy for some hours so :/
but sure, I could try.

**Comment by fawazahmed0** [comment]
@Surendrajat  I created a pull request, but I closed it because I think my code will not work in other recoveries as  some recoveries will have default.prop, prop.default and also build.prop in the same recovery.img, but only one file will have readable text, others will be binary files or might not contain data or might not some data.

So the code has to be rewritten such that, it tries to get prop details from each files such as default.prop, build.prop, prop.default , instead of just using one file
I would have written the code, but currently I am busy doing something else.

**Comment by fawazahmed0** [comment]
> 
> 
> I'll watch the queue. I am going to be busy for some hours so :/
> but sure, I could try.

@Mikasu-X14  Should I tell you the procedure then?

**Comment by fawazahmed0** [comment]
@Mikasu-X14 
make a new twrp folder in home or anywhere

cd twrp


Get device tree using twrpbuilder, remember device folder should be generated in twrp source folder, also git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git ~/twrp/device/generic/twrpbuilder

Make openjdk java 8 as default


git  the minimal twrp source: from here: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni

select the appropriate branch like android 9 etc (use omni one)
example: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/tree/twrp-9.0
steps are there at the above site:
repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0

repo sync



 
 export ALLOW_MISSING_DEPENDENCIES=true
source ./build/envsetup.sh
 lunch omni_devicename<device>-eng  (device name like RMX1831 etc, it is the name of device/company/ --device-name-) 
 make -j7 recoveryimage

After build success, terminal will show the location of twrp recovery.img

flash it , done

**Comment by Shijikori** [comment]
Thanks, I'll try when I have some time.

**Comment by Shijikori** [comment]
I am sorry but even with your explanations it's not quite understandable for me. It feels like there's a missing step or something. @fawazahmed0

**Comment by Shijikori** [comment]
I am still gonna try but it's too complicated and I might just enter the TWRP Builder queue, I just need to know what to send them.

**Comment by Shijikori** [comment]
it didn't build @fawazahmed0 . Like I said, unless you can make very detailed explanations, I cannot quite understand how to build it so I'll just wait for openings in the queue

**Comment by surendrajat** [comment]
@Mikasu-X14 "Successful" means you built it, right? In that case, you don't have to send it to us... just flash and test it. Google about the method.
@fawazahmed0 Thanks for sharing that. We will update in our free time and if you can before that you're welcome to do so.

**Comment by Shijikori** [comment]
@Surendrajat the successful build was for the wiki: https://github.com/TwrpBuilder/twrpbuilder_tree_generator/wiki
but what @fawazahmed0 told me to do didn't work and it's a bit too much in unknown grounds for me

so if the file that I did successfully build is flashable then alright, I'll try it. Otherwise, I just want to know what I have to send in order to get a recovery that works. So far, none worked. The bests that I found would flash on but then, they would simply not register screen inputs.

**Comment by surendrajat** [comment]
@Mikasu-X14 What @fawazahmed0 told you and what's in the wiki are the same thing. The thing you built is TWRP and is flashable. It's the same process we do if you send us a recovery so, no need.
About screen inputs, it can be a kernel issue as well. Find a similar device and check it's device tree, you might get some clue.

**Comment by Shijikori** [comment]
I have a little question. Since I prefer using Linux, does heimdall still work? Also, if it works, is there a special way to do it's .tar.gz files to your knowledge?

Edit: Nvm, found out that Heimdall (compared to Odin) can use .img files if I use the --RECOVERY argument. I'll try the twrp I built.

**Comment by Shijikori** [comment]
I know that all SM-J327 have the same board and are technicaly physicaly identical. Though, the P and the T versions aren't very much compatible on my W.

**Comment by Shijikori** [comment]
About the kernel, in my SM-J327W's Software Informations, my Kernel version is `3.18.14` but it specifies `gcc version 4.9.x 20150123 (prerelease) (GCC)`
Isn't it weird that I have a pre-release?

**Comment by fawazahmed0** [comment]
@Mikasu-X14  What is your android version?  you can try twrp porter by hovatek.

**Comment by fawazahmed0** [comment]
@Mikasu-X14  I can help you if you have android ver 8.1 or 9, I have those repos in my vm

**Comment by Shijikori** [comment]
I have 8.1. Probably wont get any highier than that @fawazahmed0

**Comment by fawazahmed0** [comment]
@Mikasu-X14  Try this: https://forum.hovatek.com/thread-21839.html 
https://www.youtube.com/watch?v=EeBFD7D5tQA
It might work.
Also provide your recovery.img to me

**Comment by Shijikori** [comment]
This auto porter wont work @fawazahmed0 . As far as I know, Samsung makes their own SoCs. They don't buy them from Mediatek (but they do from Qualcom). But, all Galaxy J3 that have the code SM-J327 (doesn't matter the letter at the end of it) have a universal7570 board which has a Samsung Exynos 7570 4 core CPU. So a Mediatek targeted porter wont work for this since it's not Mediatek. I can provide you my recovery through a Google Drive link there: [https://drive.google.com/open?id=1x1Rzz9w2n22VTNRCXWgUD996ngqszbIu](url)

**Comment by surendrajat** [comment]
@Mikasu-X14 check a6 or j6 repos in @TwrpBuilder org. You need to update few things from 7870 to 7570 and check their kernel repos too, how it was modified. Update all that and build. If any query, ask in @build_twrp group on tg.
I'll close this issue as it's getting out of context.

**Comment by Shijikori** [comment]
@Surendrajat I'll see what I can do. Thanks for the support! I'll try this twrp when I can
