### ISSUE TITLE
Recovery.img too large

### ISSUE THREAD

**Issue by pieterhouwen** [TwrpBuilder/twrpbuilder_tree_generator#14]
When running the make command the program exits with the following errors:

----- Making recovery image ------
/home/pieter/twrp/out/target/product/ulefone_armor_5/recovery.img maxsize=14754432 blocksize=2112 total=14913536 reserve=149952
error: /home/pieter/twrp/out/target/product/ulefone_armor_5/recovery.img too large (14913536 > [14904384 - 149952])
build/core/Makefile:957: recipe for target '/home/pieter/twrp/out/target/product/ulefone_armor_5/recovery.img' failed
make: *** [/home/pieter/twrp/out/target/product/ulefone_armor_5/recovery.img] Error 1
make: *** Deleting file '/home/pieter/twrp/out/target/product/ulefone_armor_5/recovery.img'

I'm using the stock recovery.img, how can I fix this?

**Comment by berkantkz** [comment]
@pieterhouwen Set recovery image size to something larger than 14913536 on Boardconfig.mk
