### ISSUE TITLE
Don't have a product spec for: 'gtelwifi' error

### ISSUE THREAD

**Issue by FrancescoPenasa** [TwrpBuilder/twrpbuilder_tree_generator#15]
I'm trying to build a device tree with this java to compile twpr on my samsung galaxy tab E 9.6''.
I've followed all the steps in the wiki using as source code https://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos with openjdk-8-jdk on ubuntu 19.04

At the step "Build the TWRP"
the line "lunch gtelwifi-eng" give me this error.   

`build/core/product_config.mk:249: *** Can not locate config makefile for product "gtelwifi".
Stop.
Device gtelwifi not found. Attempting to retrieve device repository from LineageOS Github
(http://github.com/LineageOS).
Repository for gtelwifi not found in the LineageOS Github repository list. If this is in error, you
may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:249: *** Can not locate config makefile for product "gtelwifi".
Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "gtelwifi".
Stop.
** Don't have a product spec for: 'gtelwifi'
** Do you have the right repo manifest?build/core/product_config.mk:249: *** Can not locate
config makefile for product "gtelwifi". Stop.
Device gtelwifi not found. Attempting to retrieve device repository from LineageOS Github
(http://github.com/LineageOS).
Repository for gtelwifi not found in the LineageOS Github repository list. If this is in error, you
may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:249: *** Can not locate config makefile for product "gtelwifi".
Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "gtelwifi".
Stop.
** Don't have a product spec for: 'gtelwifi'
** Do you have the right repo manifest?`

I would like to install twrp 3.3 is there anything I can change to make it possible?

**Comment by SscSPs** [comment]
First, You'd need to modify the tree to convert omni to lineageOS, 
Second, You need to use the full product name, like lineage_gtelwifi-eng for lunch

**Comment by FrancescoPenasa** [comment]
Ok, I decided to use omni instead of lineageOS, because I just need something based on android 6.0+ so I won't have to modify the tree.
It works until "make -j4 recoveryimage", which fails with this message.
`#### make failed to build some targets (19 seconds) ####`

**Comment by FrancescoPenasa** [comment]
I've got this warning during lnch omni_gtelwifi-eng
```
/twrp$ lunch omni_gtelwifi-eng
WARNING: device/samsung/gtelwifi/omni.dependencies file not found

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=5.1.1
TARGET_PRODUCT=omni_gtelwifi
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a9
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.0.0-20-generic-x86_64-with-Ubuntu-19.04-disco
HOST_BUILD_TYPE=release
BUILD_ID=LYZ28N
OUT_DIR=/home/ubuntu/twrp/out
============================================
```

**Comment by SscSPs** [comment]
do you realise how vague your error message is? Its a conclusion statement rather than a error message, please reade further back in the logs to see what failed and try to fix that.
Anout that warning, its fine.
