### ISSUE TITLE
failed to get codeName when building from s10e(snapdragon) recovery

### ISSUE THREAD

**Issue by Laikar** [TwrpBuilder/twrpbuilder_tree_generator#18]
I am trying to get into making twrp for s10 snapdragon devices, and when trying to build twrp from the recovery i always get

>  Failed to get codeName

I have tried the recovery image from the oficial firmware and the one the twrp app generates
Also tried boot.img from both sources but it fails to uncompress ramdisk so i guess that is not the correct file.

**Comment by androidlover5842** [comment]
https://github.com/TwrpBuilder/twrpbuilder_tree_generator/blob/master/src/main/java/com/github/twrpbuilder/Interface/Tools.java#L172

ro.build.product=codename in your build.prop

**Comment by Laikar** [comment]
Yes, i have the codename, but when runningt the jar i get this log
```
Building tree using: recovery.img
Found gzip comression in ramdisk
Dir: device/// already exist
Failed to get codeName
```
And nothing seems to be changed

**Comment by androidlover5842** [comment]
paste build.prop

**Comment by Laikar** [comment]
Here is the whole build.prop
https://pastebin.com/UAWiSJXP

**Comment by androidlover5842** [comment]
did you compressed build.prop + recovery.img  (img name=recovery.img) as zip or tar.gz then used -f option with -aik if not worked?

**Comment by Laikar** [comment]
I managed to get it done by pasting the build.prop in the same folder as recovery.img, i guess this is my fault for not knowing, but it should be specified in the wiki to try this.
Thanks for the help

**Comment by androidlover5842** [comment]
everything is outdated sorry.
