### ISSUE TITLE
Upload failed for ID2ME ID1

### ISSUE THREAD

**Issue by CurveOS** [TwrpBuilder/twrpbuilder_tree_generator#2]
Everything worked fine with creating the img to upload, but as soon as I click the Upload button it fails to upload it.

The device is rooted.

**Comment by androidlover5842** [comment]
The server was out of space so disabled write access.

**Comment by CurveOS** [comment]
Will it work now then?

**Comment by androidlover5842** [comment]
no not for now because i want to fix major bugs before starting again
