### ISSUE TITLE
errore building android 9.0

### ISSUE THREAD

**Issue by marcoarc99** [TwrpBuilder/twrpbuilder_tree_generator#20]
bootable/recovery/twrp-functions.cpp:527:17: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char, char_traits<char> >')
                std::ifstream uncompressedIfs(uncompressedLog);
                              ^               ~~~~~~~~~~~~~~~
external/stlport/stlport/stl/_fstream.h:443:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const std::basic_ifstream<char, std::char_traits<char> >' for 1st argument
class basic_ifstream : public basic_istream<_CharT, _Traits> {
      ^
external/stlport/stlport/stl/_fstream.h:462:12: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const char *' for 1st argument
  explicit basic_ifstream(const char* __s, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:471:12: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'int' for 1st argument
  explicit basic_ifstream(int __id, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:457:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  basic_ifstream() :
  ^
external/stlport/stlport/stl/_fstream.h:477:3: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
  basic_ifstream(const char* __s, ios_base::openmode __m,
  ^
bootable/recovery/twrp-functions.cpp:536:16: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char, char_traits<char> >')
        std::ifstream ifs(Source);
                      ^   ~~~~~~
external/stlport/stlport/stl/_fstream.h:443:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const std::basic_ifstream<char, std::char_traits<char> >' for 1st argument
class basic_ifstream : public basic_istream<_CharT, _Traits> {
      ^
external/stlport/stlport/stl/_fstream.h:462:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const char *' for 1st argument
  explicit basic_ifstream(const char* __s, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:471:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'int' for 1st argument
  explicit basic_ifstream(int __id, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:457:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  basic_ifstream() :
  ^
external/stlport/stlport/stl/_fstream.h:477:3: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
  basic_ifstream(const char* __s, ios_base::openmode __m,
  ^
bootable/recovery/twrp-functions.cpp:762:16: error: no matching constructor for initialization of 'std::ifstream' (aka 'basic_ifstream<char, char_traits<char> >')
        std::ifstream srcfile(src, ios::binary);
                      ^       ~~~~~~~~~~~~~~~~
external/stlport/stlport/stl/_fstream.h:462:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const char *' for 1st argument
  explicit basic_ifstream(const char* __s, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:471:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'int' for 1st argument
  explicit basic_ifstream(int __id, ios_base::openmode __mod = ios_base::in) :
           ^
external/stlport/stlport/stl/_fstream.h:443:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class basic_ifstream : public basic_istream<_CharT, _Traits> {
      ^
external/stlport/stlport/stl/_fstream.h:477:3: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
  basic_ifstream(const char* __s, ios_base::openmode __m,
  ^
external/stlport/stlport/stl/_fstream.h:457:3: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
  basic_ifstream() :
  ^
bootable/recovery/twrp-functions.cpp:763:16: error: no matching constructor for initialization of 'std::ofstream' (aka 'basic_ofstream<char, char_traits<char> >')
        std::ofstream dstfile(dst, ios::binary);
                      ^       ~~~~~~~~~~~~~~~~
external/stlport/stlport/stl/_fstream.h:542:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const char *' for 1st argument
  explicit basic_ofstream(const char* __s, ios_base::openmode __mod = ios_base::out)
           ^
external/stlport/stlport/stl/_fstream.h:550:12: note: candidate constructor not viable: no known conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'int' for 1st argument
  explicit basic_ofstream(int __id, ios_base::openmode __mod = ios_base::out)
           ^
external/stlport/stlport/stl/_fstream.h:524:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class basic_ofstream : public basic_ostream<_CharT, _Traits> {
      ^
external/stlport/stlport/stl/_fstream.h:557:3: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
  basic_ofstream(const char* __s, ios_base::openmode __m, long __protection) :
  ^
external/stlport/stlport/stl/_fstream.h:537:3: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
  basic_ofstream() :
  ^
4 errors generated.
build/core/binary.mk:620: set di istruzioni per l'obiettivo "/home/marco/Scrivania/twrp/out/target/product/gts210velte/obj/EXECUTABLES/recovery_intermediates/twrp-functions.o" non riuscito
make: *** [/home/marco/Scrivania/twrp/out/target/product/gts210velte/obj/EXECUTABLES/recovery_intermediates/twrp-functions.o] Errore 1

**Comment by berkantkz** [comment]
I need to regretfully report that this project is not maintained anymore.
