### ISSUE TITLE
Failed to uncompress ramdisk

### ISSUE THREAD

**Issue by Shedaim** [TwrpBuilder/twrpbuilder_tree_generator#3]
Tried to use the builder using a recovery.img from official Samsung ROM.
Keep getting the error: failed to uncompress ramdisk.

**Comment by berkantkz** [comment]
Sometimes these kind of issues may happen. In this case, try unpacking your recovery image using [AIK](https://github.com/TwrpBuilder/twrpbuilder_tree_generator/blob/master/src/main/resources/asset/unpackimg.sh) itself and create the tree manually.

**Comment by Shedaim** [comment]
Will try, thank you.

I tried building my device tree using mkdevice.sh or something similar from
CyanogenMod sources, but I think this may be my issue while building twrp
with Omni.

**Comment by Shedaim** [comment]
care to point me on how I manually build the tree?
Right now I got 16 filed out of unpackimg.sh.

**Comment by surendrajat** [comment]
@Shedaim Using some other device tree as a base and updating it would be a simpler approach.

Actual steps may include
- replacing `kernel` binary with your `.img-zImage` file from `spli-img/` dir
- replacing `dt.img` (if any)
- updating mount points in `recovery.fstab` acc to your `ramdisk/etc/recovery.fstab`
- updating kernel & ramdisk offsets in `kernel.mk`
- updating device codename etc.

**Comment by mohammadshaba** [comment]
which arch 32bit or 64bit
if 32bit you will face this proplem like me
i fix it by install 18.04 64bit
