### ISSUE TITLE
How to make recovery.img file from folder with device tree?

### ISSUE THREAD

**Issue by bartoll** [TwrpBuilder/twrpbuilder_tree_generator#4]
Firstly I tried to execute comand
`java -jar TwrpBuilder.jar -r recovery.img`

But I got error message:
> Building tree using: recovery.img
> failed to uncompress ramdisk

Secondly I have executed command:
`java -jar TwrpBuilder.jar -aik -r recovery.img`

And all run well but I received "device" folder with tree and don't know how to prepare *.IMG file.

Could you help me?

**Comment by berkantkz** [comment]
You need to build TWRP using that device tree. To do that, search about how to build recovery/twrp.
