### ISSUE TITLE
Failed to uncompress ramdisk

### ISSUE THREAD

**Issue by mohammadshaba** [TwrpBuilder/twrpbuilder_tree_generator#5]
When i write java -jar TwrpBuilder-1.0-SNAPSHOT.jar -r recovery.img and press enter it shows failed to uncompress ramdisk 
Please, solve this issuse

**Comment by berkantkz** [comment]
@mohammadshaba We've already been working on it.

**Comment by mohammadshaba** [comment]
thanks

**Comment by mohammadshaba** [comment]
thanks i have solve this issue by using ubuntu 18.04.1 lts 64 bit
