### ISSUE TITLE
Failed to uncompress ramdisk

### ISSUE THREAD

**Issue by dbzdivik** [TwrpBuilder/twrpbuilder_tree_generator#7]
Was trying to generate Tree for my custom device Getting error.
Pulled the recovery.img from device itself using adb shell

Currently trying on Google Cloud Ubuntu 18.04

```
root@instance-1:~/stock# java -jar builder.jar -r recovery.img
Building tree using: recovery.img
failed to uncompress ramdisk
root@instance-1:~/stock# mv recovery.img rk3288.img
root@instance-1:~/stock# java -jar builder.jar -r rk3288.img
Building tree using: rk3288.img
failed to uncompress ramdisk
root@instance-1:~/stock# 
```

**Comment by berkantkz** [comment]
This is a duplicate. Please check #3

**Comment by dbzdivik** [comment]
I already checked those issues before creating this thread.
Tried AIK
```
root@instance-1:~/stock# java -jar builder.jar -aik -r rk3288.img
Building tree using: rk3288.img
Using Android Image Kitchen to extract rk3288.img
Android Image Kitchen - UnpackImg Scriptby osm0sis @ xda-developersSupplied image: rk3288.imgUnrecognized format
.Error!
failed to uncompress ramdisk
root@instance-1:~/stock# 
```
But what i'm confused by @Surendrajat [comment](https://github.com/TwrpBuilder/twrpbuilder_tree_generator/issues/3#issuecomment-405524650)

Still if you can lookup Here is my [Repo](https://github.com/AceoS/android_device_firefly_rk3288)
Here is [Recovery.img](http://download2266.mediafire.com/6g6ra8xb34tg/gjvbzj7t30ff04w/recovery.img)

**Comment by surendrajat** [comment]
@dbzdivik that comment was about making a device tree manually using some another tree.
Given that you already have a device tree, you wouldn't need that but your tree is a mess and needs cleanup. It'd have been better if you'd have made it using this tree-generator itself.
Now, I tried your recovery and it worked in my Debian 9. I don't know what's wrong with Ubuntu 18.
<details>
<summary> Output
</summary>

```bash
sonu@xpc:~/Desktop/tmp$ java -jar TwrpBuilder-1.0-SNAPSHOT.jar -r recovery.img 
Building tree using: recovery.img
Found gzip comression in ramdisk
Making omni_rk3288.mk
Making Android.mk
Making AndroidProducts.mk
Making kernel.mk
Generating fstab
/data ext4 /dev/block/rknand_userdata
/system ext4 /dev/block/rknand_system
/cache ext4 /dev/block/rknand_cache
found rk3288 platform
Found 32 bit arch
Build fingerPrint: rockchip/rk3288/rk3288:4.4.4/KTU84Q/M2-4.4.4_20180228.145840:user/test-keys
tree ready for rk3288 at device/rockchip/rk3288
Warning :- Check recovery fstab before build
sonu@xpc:~/Desktop/tmp$ 
````
</details>

However, I've pushed that tree [here](https://github.com/Surendrajat/android_device_rockchip_rk3288.git), just fix the `fstab` etc.

**Comment by dbzdivik** [comment]
@Surendrajat Thanks for Repo.
Just a favor is there any Generator for Vendor Tree

**Comment by surendrajat** [comment]
Not a clue about that....

**Comment by dbzdivik** [comment]
So how to make TWRP if vendor tree isn't avail ?
Means I've fork a repo but need some cleanup

**Comment by surendrajat** [comment]
Vendor blobs are unnecessary for twrp building normally. You can build it without that.

**Comment by dbzdivik** [comment]
Ok. btw Current Stock ROM is 4.4 can I use omni_twrp-8.1.0 for TWRP ?

**Comment by surendrajat** [comment]
I guess not. @kirito96 may explain..
However, you can always try.

**Comment by dbzdivik** [comment]
Ok how to verify if it will work or not..

**Comment by dbzdivik** [comment]
@Surendrajat BTW 
```
root@instance-1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
root@instance-1:~# 
root@instance-1:~# cd twrp
root@instance-1:~/twrp# java -jar TwrpBuilder-1.0-SNAPSHOT.jar -r recovery.img 
Building tree using: recovery.img
failed to uncompress ramdisk
root@instance-1:~/twrp# 
```

**Comment by kirito96** [comment]
@dbzdivik you can, only if your device partition size is less than 6MB it will not work.

**Comment by dbzdivik** [comment]
@kirito96 that means no as my recovery and boot partition both are 32 MB or so...
Thanks for Help

**Comment by mohammadshaba** [comment]
which arch 32bit or 64bit
if 32bit you will face this proplem like me 
i fix it by install 18.04 64bit

**Comment by kirito96** [comment]
@dbzdivik I said if it is less than 6MB.Your recovery size it 32MB so it will work. Just build and test.

**Comment by dbzdivik** [comment]
@kirito96 any issues which can occur after building TWRP image. How to check if Image isn't suitable for Device as I don't have stock ROM for device...
Here is [TWRP](https://github.com/dbzdivik/android_device_rockchip_rk3288/releases)

**Comment by dbzdivik** [comment]
@berkantkz @Surendrajat Dunno How you guys Manage to Run Twrp Builder but I tried Several Instances and Same Result Failed to uncompress ramdisk.
Tried :- 
Google VM Instances :- Ubuntu 18.04,16, 14, Debian 9.5
Travis Build :- [Ubuntu 14.04 ](https://travis-ci.org/dbzdivik/device_Tree_Travis/builds/426282743)
Every Time same Results

**Comment by mohammadshaba** [comment]
@dbzdivik do you have e-mail ?
if yes tell me it 
i will contact you

**Comment by dbzdivik** [comment]
@mohammadshaba just add @ Gmail to my username

**Comment by Lg-PWNd** [comment]
HI , I am haveing a problem running this script, I'm trying to run it on windows 10.
I have AIK for windows, but get the following errors ,


PS C:\Users\Astr4y4L\Desktop\New folder (2)> java -jar TwrpBuilder-1.0-SNAPSHOT.jar -f recovery.img
Building tree using: recovery.img
java.lang.Exception: Cannot get resource "\umkbootimg" from Jar file.
        at com.github.twrpbuilder.Interface.Tools.extract(Tools.java:290)
        at com.github.twrpbuilder.Thread.RunCode.<init>(RunCode.java:23)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:44)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:183)

failed to uncompress ramdisk

**Comment by surendrajat** [comment]
@astrayal this is not for Windows, use some sort of Linux shell.
