### ISSUE TITLE
Lunch error while building TWRP

### ISSUE THREAD

**Issue by imaandrew** [TwrpBuilder/twrpbuilder_tree_generator#8]
I'm following the guide here: https://github.com/TwrpBuilder/twrpbuilder_tree_generator/wiki

When I run lunch, it says: 

```
Traceback (most recent call last):
  File "vendor/omni/build/tools/roomservice.py", line 341, in <module>
    os.mkdir(local_manifest_dir)
OSError: [Errno 2] No such file or directory: '.repo/local_manifests'
```

**Comment by imaandrew** [comment]
If I run make after that I get the error:

```
error: prebuilts/sdk/Android.bp:1:8: "prebuilts/sdk/tools/Android.bp": not found
ninja: error: rebuilding '/home/andrew/twrp/out/soong/.minibootstrap/build.ninja': subcommand failed
```

**Comment by imaandrew** [comment]
I think it's a problem with the sources not synced with repo as lunch checks for a file in the .repo folder which doesn't exist.

**Comment by chankruze** [comment]
> I'm following the guide here: https://github.com/TwrpBuilder/twrpbuilder_tree_generator/wiki
> 
> When I run lunch, it says:
> 
> ```
> Traceback (most recent call last):
>   File "vendor/omni/build/tools/roomservice.py", line 341, in <module>
>     os.mkdir(local_manifest_dir)
> OSError: [Errno 2] No such file or directory: '.repo/local_manifests'
> ```

`.repo/local_manifests` this file is not generated or cloned automatically with repo sync,you need this if you want to change default source code path (Device/Kernel/Vendor etc.).This overrides default manifest in .repo.

**Comment by chankruze** [comment]
> If I run make after that I get the error:
> 
> ```
> error: prebuilts/sdk/Android.bp:1:8: "prebuilts/sdk/tools/Android.bp": not found
> ninja: error: rebuilding '/home/andrew/twrp/out/soong/.minibootstrap/build.ninja': subcommand failed
> ```

This is maybe due to error while fetching source.Try clean syncing again if still have this issue,just create empty file named `Android.bp` in `prebuilts/sdk/tools/` and paste below lines in it.
```
cc_prebuilt_library_shared {
    name: "libLLVM_android",
    host_supported: true,
    target: {
        linux_glibc_x86_64: {
            srcs: ["linux/lib64/libLLVM_android.so"],
        },
        darwin_x86_64: {
            srcs: ["darwin/lib64/libLLVM_android.dylib"],
        },
        // TODO(ccross): this is necessary because the prebuilt module must have
        // all the variants that are in the source module.  Ideally Soong's
        // arch mutator should handle this.
        windows: {
            enabled: true,
        }
    },
}
cc_prebuilt_library_shared {
    name: "libclang_android",
    host_supported: true,
    target: {
        linux_glibc_x86_64: {
            srcs: ["linux/lib64/libclang_android.so"],
        },
        darwin_x86_64: {
            srcs: ["darwin/lib64/libclang_android.dylib"],
        },
        // TODO(ccross): this is necessary because the prebuilt module must have
        // all the variants that are in the source module.  Ideally Soong's
        // arch mutator should handle this.
        windows: {
            enabled: true,
        }
    },
}
java_import {
    name: "sdk-core-lambda-stubs",
    jars: ["core-lambda-stubs.jar"],
}
```
